#!/usr/bin/env bash
#
# Usage:
# ./build <community> <build-profile> <device-name>
show_help() { echo "$(grep -m1 -A1 "# Usage:" $PWD/$0)"; echo "# "; }

PWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# $1 - Community name
# $2 - Build profile name
# $3 - Device folder / nickname
do_build() {
  PROFILE_PATH="$PWD/communities/$1/$2"
  if [ -f "$PROFILE_PATH/settings.sh" ]; then
    . "$PROFILE_PATH/settings.sh"
  fi
  . "$PROFILE_PATH/$3/settings.sh"
  FILESDIR="$(mktemp -d)"
  if [ -d "$PWD/communities/$1/files" ]; then
    cp -r "$PWD/communities/$1/files/." "$FILESDIR/"
  fi
  if [ -d "$PROFILE_PATH/files" ]; then
    cp -r "$PROFILE_PATH/files/." "$FILESDIR/"
  fi
  if [ -d "$PROFILE_PATH/$3/files" ]; then
    cp -r "$PROFILE_PATH/$3/files/." "$FILESDIR/"
  fi
  set -x
  export BIN_DIR="$PROFILE_PATH/bin/$3"
  export FILES="$FILESDIR"
  set +x
  /usr/bin/env bash ./meta image \
    && : \
    || exit 1

  echo "[$0] Firmware cooked: ${BIN_DIR}/"
  ls -lh --color=auto ${BIN_DIR}
}


if [ -z "$1" ]; then
  show_help
  echo "[$0] Please specify an available community:"
  for x in $(ls $PWD/communities/); do echo "- $x" ; done
  echo "[$0] Example:"
  echo "% $0 massmesh meshnode rpi-4"
  exit 1
fi

COMMUNITY_PATH="$PWD/communities/$1"

if [ ! -d "$COMMUNITY_PATH" ]; then
  show_help
  echo "Community not found in ./communities"
  exit 1
fi

if [ -z "$2" ]; then
  show_help
  echo "Please specify a build profile:"
  for x in $(ls $COMMUNITY_PATH/ | grep -v files); do echo "- $x" ; done
  exit 1
fi

PROFILE_PATH="$COMMUNITY_PATH/$2"

if [ ! -d "$PROFILE_PATH" ]; then
  echo "Build profile not found in ./communities/$1"
  exit 1
fi

if [ -z "$3" ]; then
  show_help

  echo "[$0] Please specify a device:"
  for x in $(ls $PROFILE_PATH/); do
    [ -d $PROFILE_PATH/$x ] && \
    [ x"$x" != "xfiles" ] && \
    [ x"$x" != "xbin" ] \
      && echo "- $x" \
      || :
  done
  exit 1
fi

if [ ! -f "$PROFILE_PATH/$3/settings.sh" ]; then
  echo "Missing settings.sh for $3"
fi

do_build "$1" "$2" "$3"
