version: 2
jobs:
  test-alpine-1806:
    docker:
      - image: "alpine:latest"
    environment:
      TARGET: "ar71xx/generic"
      PROFILE: "archer-c7-v4"
      VERSION: "18.06.4"
    steps:
      - run: apk add alpine-sdk gnupg bash bzip2 coreutils curl file findutils gawk grep linux-headers ncurses-dev outils-signify perl python2 python3 rsync unzip rsync wget xz zlib-dev
      - checkout
      - run: bash ./meta image
      - run: ls ./bin/openwrt/$VERSION/$TARGET/*sysupgrade.bin

  test-alpine-snapshot:
    docker:
      - image: "alpine:latest"
    environment:
      TARGET: "ath79/generic"
      PROFILE: "tplink_archer-c7-v1"
    steps:
      - run: apk add alpine-sdk gnupg bash bzip2 coreutils curl file findutils gawk grep linux-headers ncurses-dev outils-signify perl python2 python3 rsync unzip rsync wget xz zlib-dev
      - checkout
      - run: bash ./meta image
      - run: ls ./bin/openwrt/snapshot/$TARGET/*sysupgrade.bin

  test-debian-snapshot:
    docker:
      - image: "debian:latest"
    environment:
      TARGET: "ath79/generic"
      PROFILE: "tplink_archer-c7-v1"
    steps:
      - run: apt-get update -qq
      - run: apt-get install -y build-essential curl file gawk gettext git libncurses5-dev libssl-dev python2.7 python3 signify-openbsd subversion swig unzip rsync wget zlib1g-dev
      - checkout
      - run: bash ./meta image
      - run: ls ./bin/openwrt/snapshot/$TARGET/*sysupgrade.bin

  deploy-docker:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      DOCKER_IMAGE: "aparcar/openwrt-metabuilder"
    steps:
      - run: docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
      - checkout
      - run: docker build -t "$DOCKER_IMAGE:alpine" -f ".ci/Dockerfile.alpine" .
      - run: docker build -t "$DOCKER_IMAGE:debian" -f ".ci/Dockerfile.debian" .
      - run: docker push "$DOCKER_IMAGE"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test-alpine-snapshot
      - test-alpine-1806
      - test-debian-snapshot
      - deploy-docker:
          requires:
            - test-alpine-snapshot
            - test-alpine-1806
            - test-debian-snapshot
          filters:
            branches:
              only:
                - master
